Environment:
    MsBuildPath: c:/Program Files (x86)/MSBuild/14.0/Bin/MsBuild.exe
    NUnitConsole: 
        C:/Program Files (x86)/NUnit.org/nunit-console/nunit3-console.exe
    DeploymentDir: c:/run/nunit
Solution:
    FileWatch:
        ChangeWithinPastSeconds: 3
        ExcludedDirectories: 
        - packages
        - debug
        - release
        - bin
        - obj
        - .paket
        - .git
        - .vs
    MsBuildWorkingDir: c:/DevRT
    SolutionFile: MyDev.sln
    TestProjects:
        TestsOn: true
        Directory: c:/DevRT/DevRT.Tests/bin/Debug
        Dlls:
        - DevRT.Tests
    
