Environment:
    MsBuildPath: c:/Program Files (x86)/MSBuild/14.0/Bin/MsBuild.exe
    NUnitConsole:
        C:/Program Files (x86)/NUnit.org/nunit-console/nunit3-console.exe
    DeploymentDir: c:/run/nunit
FileWatch:
    SleepMiliseconds: 1000
    ExcludedDirectories:
    - packages
    - debug
    - release
    - bin
    - obj
    - .paket
    - .git
    - .vs
    - logs
    - out
Solution:
    MsBuildWorkingDir: c:/DevRT
    SolutionFile: MyDev.sln
NUnit:
    TestProjects:
        TestsOn: true
        Directory: c:/DevRT/DevRT.Tests/bin/Debug
        Dlls:
        - DevRT.Tests